name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: nohup node app.js & # TODO: This is a hack to start the server outside npm test to schedule jobs
    - run: npm test
